version: '2'
services:
 userindex:
  build: ./matrix-geographic-user-index/
  entrypoint: /bin/sh
  tty: true
  stdin_open: true
  working_dir: /vb/
  user: test
  # https://stackoverflow.com/questions/45458052/docker-compose-port-forwarding
  # for testing we need to access synapse via localhost because that is the host name
  # name that it needs to use in order to work both in container and on local dev machine.
  network_mode: service:synapse
  volumes:
   - ./:/vb/
   - ./docker-compose-cruft/docker-home:/home/test
   - ./docker-compose-cruft/cargo-registry:/usr/local/cargo/registry
 postgres:
  image: postgis/postgis:14-3.2-alpine
  volumes:
   - ./docker-compose-cruft/db:/var/lib/postgresql/data
  environment:
   POSTGRES_PASSWORD: foobar
   POSTGRES_USER: vb
   PGDATA: /var/lib/postgresql/data
  ports:
  - "6543:5432"
 synapse:
  image: matrixdotorg/synapse:latest
  entrypoint: /start.py
  links:
   - postgres
  volumes:
   - ./docker-compose-cruft/synapse-data:/data
  environment:
    SYNAPSE_SERVER_NAME: "synapse-test.localhost"
    SYNAPSE_REPORT_STATS: "no"
  ports:
  - "8008:8008"
  - "80:80"
  - "8080:8080"
